name: ONT-Flu-Typing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abricate=1.0.1
  - abseil-cpp=20210324.2
  - absl-py=1.4.0
  - aiohttp=3.7.4.post0
  - alsa-lib=1.2.8
  - any2fasta=0.4.2
  - argtable2=2.13
  - arrow-cpp=9.0.0
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=23.1.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - bcftools=1.17
  - bedtools=2.31.0
  - binutils_impl_linux-64=2.40
  - bioawk=1.0
  - biopython=1.81
  - blast=2.14.0
  - blast-legacy=2.2.26
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=3.1.0
  - chopper=0.5.0
  - clang=16.0.1
  - clang-16=16.0.1
  - click=8.1.3
  - clustalo=1.2.4
  - clustalw=2.1
  - coreutils=9.3
  - cryptography=39.0.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - curl=7.87.0
  - deprecated=1.2.14
  - entrez-direct=16.2
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gast=0.5.3
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - glog=0.6.0
  - google-auth=2.17.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpc-cpp=1.45.2
  - grpcio=1.45.0
  - gsl=2.7
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - htslib=1.17
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - intervaltree=3.1.0
  - jpeg=9e
  - k8=0.2.5
  - kaleido-core=0.2.1
  - keras=2.8.0
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang-cpp16=16.0.1
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgomp=12.2.0
  - libgoogle-cloud=1.40.2
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm16=16.0.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsanitizer=12.2.0
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.2.13
  - longshot=0.4.5
  - lz4-c=1.9.4
  - mafft=7.520
  - mappy=2.26
  - markdown=3.4.3
  - markupsafe=2.1.2
  - mathjax=2.7.7
  - medaka=1.8.0
  - miniasm=0.3
  - minimap2=2.26
  - multidict=6.0.4
  - muscle=5.1
  - nanoget=1.18.1
  - nanomath=1.3.0
  - nanoplot=1.41.3
  - nccl=2.15.5.1
  - ncurses=6.3
  - nextflow=23.04.1
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - oauthlib=3.2.2
  - ont-fast5-api=4.1.1
  - openjdk=17.0.3
  - openssl=1.1.1u
  - opt_einsum=3.3.0
  - orc=1.7.6
  - packaging=23.1
  - paml=4.10.6
  - pandas=2.0.2
  - parasail-python=1.3.3
  - parquet-cpp=1.5.1
  - pcre=8.45
  - pcre2=10.40
  - perl=5.32.1
  - perl-algorithm-diff=1.201
  - perl-archive-tar=2.40
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-featureio=1.6.905
  - perl-bio-samtools=1.43
  - perl-bio-searchio-hmmer=1.7.3
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.8
  - perl-bioperl-core=1.7.8
  - perl-bioperl-run=1.007003
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.50
  - perl-class-data-inheritable=0.09
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-data-dumper=2.183
  - perl-db_file=1.858
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.58
  - perl-encode=3.19
  - perl-encode-locale=1.05
  - perl-exception-class=1.45
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.15
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-spec=3.48_01
  - perl-getopt-long=2.54
  - perl-html-parser=3.81
  - perl-html-tagset=3.20
  - perl-http-cookies=6.10
  - perl-http-daemon=6.16
  - perl-http-date=6.05
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.075
  - perl-io-string=1.08
  - perl-io-tty=1.16
  - perl-io-zlib=1.14
  - perl-ipc-run=20200505.0
  - perl-json=4.10
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-lwp-mediatypes=6.04
  - perl-lwp-simple=6.39
  - perl-mime-base64=3.16
  - perl-module-build=0.4234
  - perl-net-http=6.22
  - perl-net-ssleay=1.92
  - perl-ntlm=1.09
  - perl-parent=0.241
  - perl-path-tiny=0.124
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.63
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-sub-uplevel=0.2800
  - perl-test-deep=1.130
  - perl-test-differences=0.69
  - perl-test-exception=0.43
  - perl-test-fatal=0.016
  - perl-test-most=0.38
  - perl-test-warn=0.37
  - perl-test-warnings=0.031
  - perl-text-diff=1.45
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.32
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-uri=5.17
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-xpathengine=0.14
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.5.1
  - plotly=5.14.1
  - poa=2.0
  - pooch=1.7.0
  - progressbar33=2.4
  - protobuf=3.20.3
  - pthread-stubs=0.4
  - pyarrow=9.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.7.0
  - pyopenssl=23.1.1
  - pysam=0.21.0
  - pysocks=1.7.1
  - pyspoa=0.0.3
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-edlib=1.3.9
  - python-flatbuffers=23.5.26
  - python-kaleido=0.2.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - pyu2f=0.1.5
  - racon=1.5.0
  - re2=2022.06.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - s2n=1.0.10
  - samtools=1.17
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sqlite=3.42.0
  - sysroot_linux-64=2.12
  - t-coffee=12.00.7fb08c2
  - tar=1.34
  - tenacity=8.2.2
  - tensorboard=2.8.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.8.1
  - tensorflow-base=2.8.1
  - tensorflow-estimator=2.8.1
  - termcolor=2.3.0
  - tk=8.6.12
  - typing-extensions=4.6.2
  - typing_extensions=4.6.2
  - tzdata=2023c
  - unzip=6.0
  - urllib3=2.0.2
  - vcftools=0.1.16
  - viennarna=2.5.1
  - werkzeug=2.3.4
  - wget=1.20.3
  - wheel=0.40.0
  - wrapt=1.15.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yarl=1.9.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2